<html>
<head>
<title>TestNG:  C:/Users/SATTDN20.03.08/Desktop/myProject/selenium/Selenium/SeleniumTest1/Testcases/RailWay/railways</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>C:/Users/SATTDN20.03.08/Desktop/myProject/selenium/Selenium/SeleniumTest1/Testcases/RailWay/railways</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>12/2/0</td>
</tr><tr>
<td>Started on:</td><td>Mon Feb 01 08:47:52 ICT 2021</td>
</tr>
<tr><td>Total time:</td><td>243 seconds (243960 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='Testcases.RailWay.railways.TC05_LoginSeveralTimes.TC05()'><b>TC05</b><br>Test class: Testcases.RailWay.railways.TC05_LoginSeveralTimes<br>Parameters: {msg_loginSeveralTimes=You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.}</td>
<td><div><pre>java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at org.testng.Assert.assertEquals(Assert.java:463)
	at Testcases.RailWay.railways.TC05_LoginSeveralTimes.TC05(TC05_LoginSeveralTimes.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
</pre></div><a href='#' onClick='toggleBox("stack-trace108333023", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace108333023'><pre>java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at org.testng.Assert.assertEquals(Assert.java:463)
	at Testcases.RailWay.railways.TC05_LoginSeveralTimes.TC05(TC05_LoginSeveralTimes.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
</pre></div></td>
<td>8</td>
<td>Testcases.RailWay.railways.TC05_LoginSeveralTimes@79698539</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC08_LoginWithNotActivatedAccount.TC08()'><b>TC08</b><br>Test class: Testcases.RailWay.railways.TC08_LoginWithNotActivatedAccount<br>Parameters: {}</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at Testcases.RailWay.railways.TC08_LoginWithNotActivatedAccount.TC08(TC08_LoginWithNotActivatedAccount.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
</pre></div><a href='#' onClick='toggleBox("stack-trace1574053815", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1574053815'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at Testcases.RailWay.railways.TC08_LoginWithNotActivatedAccount.TC08(TC08_LoginWithNotActivatedAccount.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
</pre></div></td>
<td>3</td>
<td>Testcases.RailWay.railways.TC08_LoginWithNotActivatedAccount@38082d64</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='Testcases.RailWay.railways.TC01_LoginWithValidAccount.TC01()'><b>TC01</b><br>Test class: Testcases.RailWay.railways.TC01_LoginWithValidAccount<br>Parameters: {password=123456789, username=thanh123@logigear.com}</td>
<td></td>
<td>5</td>
<td>Testcases.RailWay.railways.TC01_LoginWithValidAccount@7a5d012c</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC02_LoginWithBlankUsername.TC02()'><b>TC02</b><br>Test class: Testcases.RailWay.railways.TC02_LoginWithBlankUsername<br>Parameters: {msg_BlankLogin=There was a problem with your login and/or errors exist in your form.}</td>
<td></td>
<td>3</td>
<td>Testcases.RailWay.railways.TC02_LoginWithBlankUsername@3fb6a447</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC03_LoginWithInvalidPassword.TC03()'><b>TC03</b><br>Test class: Testcases.RailWay.railways.TC03_LoginWithInvalidPassword<br>Parameters: {msg_InvalidLogin=Invalid username or password. Please try again.}</td>
<td></td>
<td>3</td>
<td>Testcases.RailWay.railways.TC03_LoginWithInvalidPassword@79b4d0f</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC04_LoginFromBookTicket.TC04()'><b>TC04</b><br>Test class: Testcases.RailWay.railways.TC04_LoginFromBookTicket<br>Parameters: {loginPage=Login Page}</td>
<td></td>
<td>1</td>
<td>Testcases.RailWay.railways.TC04_LoginFromBookTicket@6b2fad11</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC06_HomeLogged.TC06()'><b>TC06</b><br>Test class: Testcases.RailWay.railways.TC06_HomeLogged<br>Parameters: {changePassword=Change password, myTicketPage=Manage Tickets}</td>
<td></td>
<td>6</td>
<td>Testcases.RailWay.railways.TC06_HomeLogged@73f792cf</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC07_CreateAccount.TC07()'><b>TC07</b><br>Test class: Testcases.RailWay.railways.TC07_CreateAccount<br>Parameters: {registrationConfirmed=Registration Confirmed! You can now log in to the site.}</td>
<td></td>
<td>3</td>
<td>Testcases.RailWay.railways.TC07_CreateAccount@2ed94a8b</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC09_ChangeNewPassword.TC09()'><b>TC09</b><br>Test class: Testcases.RailWay.railways.TC09_ChangeNewPassword<br>Parameters: {passwordChanged=Your password has been updated!}</td>
<td></td>
<td>7</td>
<td>Testcases.RailWay.railways.TC09_ChangeNewPassword@dfd3711</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC10_RegisterWithInvalidAccount.TC10()'><b>TC10</b><br>Test class: Testcases.RailWay.railways.TC10_RegisterWithInvalidAccount<br>Parameters: {InvalidRegister=There're errors in the form. Please correct the errors and try again.}</td>
<td></td>
<td>3</td>
<td>Testcases.RailWay.railways.TC10_RegisterWithInvalidAccount@42d3bd8b</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC11_RegisterWithInvalidAccount.TC11()'><b>TC11</b><br>Test class: Testcases.RailWay.railways.TC11_RegisterWithInvalidAccount<br>Parameters: {IDLength=Invalid ID length, InvalidRegister=There're errors in the form. Please correct the errors and try again., PasswordLength=Invalid password length}</td>
<td></td>
<td>3</td>
<td>Testcases.RailWay.railways.TC11_RegisterWithInvalidAccount@26ba2a48</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC14_BookTicket.TC14()'><b>TC14</b><br>Test class: Testcases.RailWay.railways.TC14_BookTicket<br>Parameters: {departFrom=Phan Thiết, ticketAmount=1, arriveAt=Nha Trang, departDate=2/4/2021, bookedTicket=Ticket booked successfully!, seatType=Hard bed}</td>
<td></td>
<td>12</td>
<td>Testcases.RailWay.railways.TC14_BookTicket@5f2050f6</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC15_BookTicketFrTrainTimetable.TC15()'><b>TC15</b><br>Test class: Testcases.RailWay.railways.TC15_BookTicketFrTrainTimetable<br>Parameters: {departFrom=Huế, departArrive=Sài Gòn}</td>
<td></td>
<td>5</td>
<td>Testcases.RailWay.railways.TC15_BookTicketFrTrainTimetable@3b81a1bc</td></tr>
<tr>
<td title='Testcases.RailWay.railways.TC16_CancelTicket.TC16()'><b>TC16</b><br>Test class: Testcases.RailWay.railways.TC16_CancelTicket<br>Parameters: {departFrom=Phan Thiết, ticketAmount=1, arriveAt=Nha Trang, departDate=2/4/2021, seatType=Hard bed}</td>
<td></td>
<td>12</td>
<td>Testcases.RailWay.railways.TC16_CancelTicket@64616ca2</td></tr>
</table><p>
</body>
</html>